services:
  - type: web
    name: la-lavanderia
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT --threads=4 wsgi:app
    healthCheckPath: /
    healthCheckInterval: 300
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
