services:
  - type: web
    name: la-lavanderia
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app:app
    healthCheckPath: /
    autoDeploy: true
